services:
  navidrome:
    image: docker.io/deluan/navidrome:0.53.3
    ports:
      - ${PORT:-4533}:4533
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ${MISIC_DIR}
        target: /music
        read_only: true
